# Generated by Django 5.0.2 on 2024-02-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
